### ISSUE TITLE
storeItem seems to store in chrome LocalStorage

### ISSUE THREAD

**Issue by newuser44** [TheCocoaProject/cordova-plugin-nativestorage#132]
It seemed like this was only build to work with mobile app storage.  
We build a version of our ionic app for production demo.  
Looking at the build all the values that we setup with storeItem  are in the local storage.   
Not what we expecting.  Is this suppose to happen?

**Comment by JeffBerman** [comment]
When running your app in a desktop browser, setItem stores its stuff in local storage.

It says so here: https://github.com/TheCocoaProject/cordova-plugin-nativestorage/wiki/How-it-works

**Comment by GillesC** [comment]
The plugin was developed to address the issue of local storage on mobile devices. However, this issue was (is? ) not present in browsers. In addition, we wanted not to add more complexity than necessary thus no database implementation was used.

**Comment by newuser44** [comment]
@JeffBerman 
I'm not actually sure what this means 

> Browser (only for testing)
JSON in combination with localStorage

@GillesC 

I can see that.   The reason we were kind of pushed to use this plugin was because we were storing some data in local storage.   We were hoping to take out and I guess our assumption was that it wouldn't work for browser.

**Comment by JeffBerman** [comment]
The Native Storage plugin was created so that Cordova apps running on mobile devices could store data in more permanent locations than local storage. When developing a Cordova app, it is sometimes convenient to test it in a desktop web browser instead of on a mobile device, so the Native Storage developers added support for this. They did this by writing to local storage, which allows Cordova app developers to test their code in a web browser. You obviously wouldn't want to run a production Cordova app in the browser using this plugin, but it's good enough for testing your code.

Hence, "Browser (only for testing)".

**Comment by newuser44** [comment]
> You obviously wouldn't want to run a production Cordova app in the browser using this plugin, but it's good enough for testing your code.

That is exactly what we do for support purpose we use the ionic build browser and push it out to production.   Again not used by our customers but by support users.    Thus we were trying to eliminate some local storage values.
