### ISSUE TITLE
Update F.A.Q.

### ISSUE THREAD

**Issue by dalslandan200** [TheCocoaProject/cordova-plugin-nativestorage#133]
I read the documentation and as of 2019 this seems to not be an issue. The applicationData (anything stored with this plugin) seems to be successfully removed when the application is uninstalled. So, if this is not an issue anymore, is it possible to remove this from F.A.Q. for better understanding:

>Oh no my stored data is not cleared after reinstalling my application. How do I resolve this 'issue'?
You need to set android:allowBackup=false in the application tag of AndroidManifest.xml. More information at this issue and this StackOverflow question.

**Also `android:allowBackup=false` is used incorrectly in the information above.**

This is what the Android documentation states:
> Whether to allow the application to participate in the backup and restore infrastructure. If this attribute is set to false, no backup or restore of the application will ever be performed, even by a full-system backup that would otherwise cause all application data to be saved via adb. The default value of this attribute is true.

Source: https://developer.android.com/guide/topics/manifest/application-element

I could be wrong, but this is how I have interpreted it.

**Comment by GillesC** [comment]
This F.A.Q. question relates to unwantedly restoring app data when the application is reinstalled.
This is due to the data being backed up. If you set the `android:allowBackup` to false, the app will not be included in the back-up procedure. However, if this is not the case anymore in as of 2049, could you please provide a link to the documentation so I can update the F.A.Q.?

**Comment by GillesC** [comment]
closed due to inactivity.
