### ISSUE TITLE
Implicit conversion loses integer precision warnings

### ISSUE THREAD

**Issue by BenjaminConant** [TheCocoaProject/cordova-plugin-nativestorage#24]
Getting two warnings from NativeStorage.m on build... build succeeds but would like to know whats going on .. 
<img width="403" alt="screen shot 2016-06-13 at 3 05 16 pm" src="https://cloud.githubusercontent.com/assets/7742063/16019720/69df5390-3178-11e6-8e23-929c0b91a59a.png">
<img width="541" alt="screen shot 2016-06-13 at 3 05 29 pm" src="https://cloud.githubusercontent.com/assets/7742063/16019723/6bce37b6-3178-11e6-9d23-52ecd820a5fa.png">

**Comment by alokrajiv** [comment]
@BenjaminConant Hi, I'm assuming the issue shot because of 64-bit unsigned long being 64bit but the int is 32-bit. so there is precision loss, I'm assuming for very large number with representations above said limits. But, I'll let @GillesC comment as well because I'm not very familiar with the objective-c implementation at that particular point.

**Comment by GillesC** [comment]
@BenjaminConant Alokrajiv is correct. Via `integerValue` an NSInteger is returned. But the NSUserDefaults expects an int and not a NSInteger, i.e. it stores an int nog a NSInteger in iOS. So it must cast the NSInteger to an int. This warning just says that there could be a precision loss when casting NSInteger to an int. This is only the case when storing very large numbers by means of the `putInt` method. This isn't the case when using the newer API (as of version 2.0) with the `getItem` and `setItem` API. 

I hope I've giving you the information you needed? If that's the case I will close this issue :)

**Comment by GillesC** [comment]
@BenjaminConant alokrajiv is correct. In Android the number is also stored as an integer and not as a long (which is a NSInteger in iOS). Because of this reason I've opted to store it as an int. So the same functionality is provided by Android and iOS. But now I've changed the code so an NSInteger is stored, which resolves your 'problem', i.e. the generated warning.

This change is only made in the experimental repo through Github. To install this version please uninstall the current plugin:
`cordova plugin remove cordova-plugin-nativestorage`
And add the plugin via Github:
`cordova plugin add https://github.com/TheCocoaProject/cordova-plugin-nativestorage`
