### ISSUE TITLE
Limit On String Size

### ISSUE THREAD

**Issue by lovestoprogram** [TheCocoaProject/cordova-plugin-nativestorage#31]
Is there a limit on how large an object/string can be for it to be successfully saved? Also, could error code 1 " native write failed" imply that the device is out of memory?

**Comment by GillesC** [comment]
Error code 1 implies that simply the native mechanisms were unable to perform a write to the disk.
I'm unable to give you a more specific answer because the docs of the native mechanisms are unclear about what could be wrong, possible because there are so many different things that could be wrong.

More over size limit see the [README](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#when-to-use-the-plugin). There can't be really one 'static' limit size because all devices are different and the free space on all these devices are also different.

More info:

- Storage of a string value in Android: http://stackoverflow.com/questions/8516812/shared-preferences-max-length-of-a-single-value
- Storage of a string value in iOS: http://stackoverflow.com/questions/16409658/ios-and-xcode-how-long-of-a-string-can-be-stored-in-nsuserdefault

But note that Cordova itself can be a limited factor on how large data can be when 'sending' it to the native side, and retrieving it from the native side.

**Comment by lovestoprogram** [comment]
Thank you for your prompt and detailed response.
