### ISSUE TITLE
error.code undefined

### ISSUE THREAD

**Issue by dmr07** [TheCocoaProject/cordova-plugin-nativestorage#46]
Sorry to be nuisance, but I was hoping to do an insert when no object is found through the error.code API you provided in your documentation. 

It's however returning me a string. Will there be a future update to make this available by any chance?

**Comment by GillesC** [comment]
Could you please provide the platform where this inconsistency resides?

**Comment by danielmeng07** [comment]
Ionic v1.3.1 
Chrome v54.0.2840.71
Mac OS v10.12.1

I have not tested this on the emulator or the phone. Strictly in browser.

**Comment by anwserman** [comment]
This is happening with the Browser too, on Windows 10/Chrome.

`mainHandle.js:87 Uncaught TypeError: error is not a function(…)
StorageHandle.set @ mainHandle.js:87
(anonymous function) @ VM65:34
dispatch @ jquery-3.1.1.min.js:3
q.handle @ jquery-3.1.1.min.js:3`

**Comment by GillesC** [comment]
@anwserman  Are you also getting a "error.code undefined" error. Otherwise, please open a new issue [here](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/issues). Or see [this issue](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/issues/45) which has had the same error. And comment there, if suited for your problem.

**Comment by GillesC** [comment]
@danielmeng07 Thank you for the information. I will look into it, when I've got same time.

**Comment by probil** [comment]
So, I found the bug.
On android device it's `error.code`, in browser -> `error.code.code`.

**Comment by alokrajiv** [comment]
@probil thanks.. will fix and push soon!

**Comment by alokrajiv** [comment]
Sorry for delay guys, but this issue was fixed in PR #108
