### ISSUE TITLE
duplicate JSON.parse means getItem with LocalStorage handler tries to parse an object not a string

### ISSUE THREAD

**Issue by PrimarDarren** [TheCocoaProject/cordova-plugin-nativestorage#47]
Anonymous function within storageHandlerDelegate within StorageHandle.prototype.getItem does JSON.parse but LocalStorage get operation also does JSON.parse.

**Comment by GillesC** [comment]
Please provide some more information on why you have closed this issue. So this wouldn't be confusing when read in the future. Just be correct ;)

**Comment by JeffBerman** [comment]
This actually _is_ an issue.  When using NativeStorage.setItem() on the browser platform, the object is stringified twice.  When using NativeStorage.getItem(), it is parsed twice.  While odd, this doesn't actually hurt anything when using NativeStorage to do both actions.

It breaks, however, when using NativeStorage to retrieve an item that was originally written by window.localStorage.  In my case, I'm upgrading our app, which previously used localStorage, to use NativeStorage.  At app startup, the code uses NativeStorage to retrieve some data; if it exists, it knows it came from native storage and goes on its way.  If it doesn't exist in native storage, then it converts it by retrieving it from local storage and writing it out to native storage.  This works great on a phone, but fails when run in the browser because on a browser local storage is used behind the scenes, and the double-parse causes an error (because the data was originally written with only one stringify).
