### ISSUE TITLE
Help with android SharedPreferences.

### ISSUE THREAD

**Issue by tdesc** [TheCocoaProject/cordova-plugin-nativestorage#50]
Hello, 
I need to read string variable from javascript code, which I need to set from android Native code.
`
         public static final String PREFS_NAME = "NativeStorage";
         public static final String REFFERER = "refferer";

         SharedPreferences mPrefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE);

          Editor edit = mPrefs.edit();
    	  edit.putString(REFFERER, referrerString);
    	  edit.commit();` 

Getting this from javascript returns null
` NativeStorage.getString("refferer",function(result), function(err)`

Any advices, how to put string in android java and get it from javascript NativeStorage, highly appreciate.

**Comment by tdesc** [comment]
with context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE) in both NativeStorage and my java code fix this issue.

**Comment by GillesC** [comment]
1. Coding issues should be asked on Stackoverflow, with [our tag](http://stackoverflow.com/questions/tagged/cordova-nativestorage).
2. This issue was also discussed in [this thread](http://stackoverflow.com/questions/25657749/cordova-plugin-expose-js-variable-android-cardflight/39331899#39331899). And you don't need to change any code in the plugin.
3. Changing the plugin's code is not really good practice, because the plugin need to be manual adjusted (by you) with every update.
4. A similar problem (and solution) can be found in [the documentation](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#faq). So you should first read the documentation before opening issues.
