### ISSUE TITLE
Problem with Android 5.0.1 and iOS 9

### ISSUE THREAD

**Issue by pataar** [TheCocoaProject/cordova-plugin-nativestorage#69]
Thank you for this plugin, works great. There is a small issue on some platforms though. 
I'm getting an error on both iOS 9 and Android 5.0.1 concerning the LocalStorageHandle.

I've attached screenshots to show where it goes wrong. Do you have any idea how to solve these?

**iOS 9**
![screen shot 2017-03-08 at 16 43 53](https://cloud.githubusercontent.com/assets/3403851/23711131/4281175a-041f-11e7-99c1-b277747e181c.png)

**Android 5.0.1**
![screen shot 2017-03-08 at 16 47 47](https://cloud.githubusercontent.com/assets/3403851/23711132/433c16d6-041f-11e7-957c-806d8581de71.png)

Thanks in advance!

**Comment by GillesC** [comment]
Hello

This should be solved in PR #68.
This version is, however, not yet published to NPM.

Therefore, please [reinstall the developement version of the plugin](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#reinstallinginstalling-developer-version).

If the issue is resolved, please consider closing the issue.

**Comment by pataar** [comment]
Hello Gilles,

Thanks, I'll look forward to the release.

**Comment by GillesC** [comment]
Any news on your problem? Is it resolved?

**Comment by pataar** [comment]
Sorry for my late reaction. Tested it, and it seems to work. Thanks!

**Comment by GillesC** [comment]
Published to NPM
