### ISSUE TITLE
ReferenceError: NativeStorage is not defined in Android 4.4.2

### ISSUE THREAD

**Issue by fgagneten** [TheCocoaProject/cordova-plugin-nativestorage#82]
I get the following error on android 4.4.2:

     ReferenceError: NativeStorage is not defined
                                                              at file:///android_asset/www/scripts/login/login.service.js:109:21
                                                              ...
                                                              ...

The following line (109) is:

    NativeStorage.setItem('user', data.user)

In my my phone (Android 7.0) works perfect but on android with version 4.4 not working. I don't know why. 

This is version of the plugin:

    cordova-plugin-nativestorage 2.2.2 "NativeStorage"

Anyone can help me?

Thanks

**Comment by dotnetCarpenter** [comment]
Did you call `NativeStorage.setItem('user', data.user)` before `deviceready` or after?

`NativeStorage` does not exist before `deviceready`.

```js
document.addEventListener('deviceready', onDeviceReady, false)

function onDeviceReady() {
  document.removeEventListener('deviceready', onDeviceReady, false)
  // now you can use NativeStorage
  NativeStorage.setItem('user', data.user)
}
```

**Comment by alokrajiv** [comment]
Please reconsider before posting such questions in the Issues section.

The issue page is meant to post issues, errors and other problems related to our plugin.
Your problem is a usage problem and thus should be posted in a forum such as StackOverflow (where you can use our tag [cordova-nativestorage](https://stackoverflow.com/questions/tagged/cordova-nativestorage)).

I am going to close this issue and will be more than happy to answer such questions in SO.

Thank you but sorry again!
