### ISSUE TITLE
I want to store the current page

### ISSUE THREAD

**Issue by Nikkolas** [TheCocoaProject/cordova-plugin-nativestorage#90]
Hi, i want to know how can i store the current html page? I have several html pages in my app and when the user leaves the application, I want that when it restarts it arrives on the same page.

Do you know what is the best way to do this?

Thank you for your help.

**Comment by GillesC** [comment]
Thank you for using our plugin.
The issue page is meant to post issues, errors and other problems related to our plugin.
Your problem is a programming problem, and thus should be posted in a forum such as StackOverflow (where you can use our tag [cordova-nativestorage](https://stackoverflow.com/questions/tagged/cordova-nativestorage)).

For this reason, I will close this issue and will answer your question in SO to discourage other people to also use issues for programming problems.
