### ISSUE TITLE
Values persisting across app uninstall and install on Android?

### ISSUE THREAD

**Issue by funkyvisions** [TheCocoaProject/cordova-plugin-nativestorage#92]
Have you seen any issue where settings are being persisted across app uninstall and reinstall (which we don't want)?  We are testing on several Android devices and we have 1 that behaves this way.  All the others have the data wiped.  iOS seems to behave correctly as well.

**Comment by GillesC** [comment]
This is documented in the readme, see F.A.Q.
This is the default behaviour of SharedPreferences in Android.
To tackle this issue, you could clear the NativeStorage stored values (`NativeStorage.clear(<success-callback>, <error-callback>);`) if your app has just been installed for the first time. 

Thus:
- NativeStorage.getItem("isFirstTime",...)
- If it is the first time you access 'isFirstTime' reference NativeStorage will give an error code 2 (i.e. Item not Found)
- If that is the case: clear nativestorage
- Otherwise: NativeStorage.setItem IsFirstTime to false

**Comment by funkyvisions** [comment]
Oh I missed that... thanks!

**Comment by alokrajiv** [comment]
Seems this is not an issue. Closing :)
