### ISSUE TITLE
I want to check whether it is the first visit in my app

### ISSUE THREAD

**Issue by yenoss** [TheCocoaProject/cordova-plugin-nativestorage#93]
hi !

thank u for your cordova - library! so useful!

I want to check whether it is the first visit in my app

here's  my sudo code.

```
// first way.
NativeStorage.getItem("visitFlag",function(obj){
},function(err){
 if err = no keys, then setItem("vistFlag",true)
})

// second way.
NativeStorage.keys(function(obj){
if (  !'vistFlag' in myObj), then setItem("vistFlag",true)
},function(err){
})
```

I just find two ways. 

what is  best practice ? plz give me a some hit!

thank u

**Comment by alokrajiv** [comment]
Thank you for using the plugin. We are very happy you find it useful.

The issue page is meant to post issues, errors and other problems related to our plugin.
Your problem is a usage problem and thus should be posted in a forum such as StackOverflow (where you can use our tag [cordova-nativestorage](https://stackoverflow.com/questions/tagged/cordova-nativestorage)).

I am going to close this issue and will be more than happy to answer such questions in SO.

Thank you but sorry again!

**Comment by yenoss** [comment]
ok! i got it.

thanks!
